### PR TITLE
Fixed Instant death mishadling of entity health

### PR DESCRIPTION
**Pull request by Cwoodyard**
Fixed the mishandling of an entities health with InstantDeath enchant that would cause item loss and no registration of entities death.

### CODE REVIEW

**Comment by democat3457** [comment]
Wouldn't this enchantment, with the given changes, be negated if the target had armor that greatly negated magic damage?

**Comment by Tfarcenim** [comment]
or really any kind of damage cap, the point is to cause instant death regardless of protections.

**Comment by democat3457** [comment]
Could try whatever the 1.15 variant of `EntityLivingBase.onDeath(DamageSource.MAGIC)` or `EntityLivingBase.onKillCommand()` is (from 1.12).

**Comment by Cwoodyard** [comment]
I'll see if I can get that part addressed and will fix it. Thanks for pointing it out. :)

**Comment by Cwoodyard** [comment]
Just checked, Magic damage bypasses armor and at most I just need to add a way to get magic resistance then negate it.

**Comment by Cwoodyard** [comment]
I cant directly find a value to set an entities health to 0 unless I am dealing with the issues before.

**Comment by democat3457** [comment]
Does this negate the magic resistance as well?

**Comment by Cwoodyard** [comment]
@democat3457 i believe so.

**Comment by Tfarcenim** [comment]
found a solution for this that preserves mechanics

**Pull request closed without merging**
